name: Quick Test Build

on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "README.md"
      - "fastlane/**"
      - "assets/**"
      - ".github/**/*.md"
      - ".github/FUNDING.yml"
      - ".github/ISSUE_TEMPLATE/**"

permissions:
  contents: write

jobs:
  build_quick:
    name: Quick Universal Debug Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_KEY }}
          cache-cleanup: on-success

      - name: Setup and Generate Protobuf
        uses: ./.github/actions/setup-protobuf

      - name: Setup FFTW for Android
        uses: ./.github/actions/setup-fftw

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate debug keystore
        run: |
          keytool -genkeypair -v \
            -keystore app/persistent-debug.keystore \
            -alias androiddebugkey \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass android -keypass android \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Build Universal Debug APK (No Lint)
        run: ./gradlew --console=plain assembleUniversalFossDebug --warning-mode summary -x lint -x lintUniversalFossDebug
        env:
          PULL_REQUEST: "false"
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_SECRET: ${{ secrets.LASTFM_SECRET }}

      - name: Upload APK
        uses: actions/upload-artifact@v6
        with:
          name: app-universal-debug
          path: app/build/outputs/apk/universalFoss/debug/*.apk
